CREATE DATABASE 2at_db;
USE 2at_db;
CREATE TABLE alunos (
    numero_chamada INT PRIMARY KEY,
    nome VARCHAR(50)
);
DELIMITER $$
CREATE PROCEDURE CadastrarAluno(
IN n_chamada INT,
IN p_nome VARCHAR(50)
)
BEGIN
INSERT INTO alunos (numero_chamada, nome)
VALUES (n_chamada, p_nome);
END $$
DELIMITER ;
CALL CadastrarAluno(1, 'ANA VITORIA LEAL KEDROSKI');
CALL CadastrarAluno(2, 'ARTHUR FERNANDO LORENZINI');
CALL CadastrarAluno(4, 'DANIEL BIEHL STIWERS');
CALL CadastrarAluno(5, 'EDUARD ZAYON PORTELA SUICA DOS SANTOS');
CALL CadastrarAluno(6, 'EDUARDO AUGUSTO KLAVA CORREA');
CALL CadastrarAluno(7, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(8, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(9, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(10, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(11, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(12, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(13, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(14, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(15, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(16, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(17, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(19, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(20, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(21, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(22, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(23, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(24, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(25, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(26, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(27, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(28, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(29, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(30, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(31, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(32, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(33, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(34, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno(35, 'FLAVIA WACHTER BUZZATTO');

